### ISSUE TITLE
Is this distribution being maintained?

### ISSUE THREAD

**Issue by karenetheridge** [acme/data-page#2]
Hi,
I'm a big fan of Data::Page, and use it regularly via DBIx::Class's paged resultsets.  Is this module being maintained? I've identified a number of small fixes, some to fix bugs and some to clean up the tooling+metadata. If you're not interested in maintaining it anymore, I'd be happy to take it off your hands. My cpan id is 'ETHER' and Neil Bowers, ilmari and mst should be able to verify for you that I'm a real human being :)

cheers!

**Comment by acme** [comment]
Hi Karen,

I don't really use this module any more. Thanks for offering to take it over. Please be gentle ;-)

`Added ETHER to co-maintainers of Data::Page.`

Regards, Leon

**Comment by karenetheridge** [comment]
Thank you very much! I will try :)
